// ------------------------------------------------------------------------------
// <auto-generated>
// Bu kod araç tarafından oluşturuldu.
// Çalışma Zamanı Sürümü:4.0.30319.18033
// 
// Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
// kod yeniden üretildiğinde kaybolur.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using Microsoft.VisualBasic;


namespace MVCe_CommerenceApp.My.Resources
{

    // Bu sınıf StronglyTypedResourceBuilder sınıfı tarafından
    // ResGen veya Visual Studio gibi bir araç kullanılarak otomatik olarak üretildi.
    // Üye eklemek veya kaldırmak için, .ResX dosyanızı düzenleyin ve ResGen'i
    // /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    // <summary>
    // Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    // </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        // <summary>
        // Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        // </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("WebAPI_VB_NoAuth.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        // <summary>
        // Türü kesin belirtilmiş bu kaynak sınıfını kullanarak tüm kaynak aramaları için geçerli iş parçacığının CurrentUICulture
        // özelliğini geçersiz kılar.
        // </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}